version: "3.8"

services:
  frontend:
    image: peterlouisx2005/obesense-frontend:latest
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: peterlouisx2005/obesense-backend:latest
    build: /backend
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
